"use strict";

NO_BINDING;

var VAR_BINDING = NO_BINDING;

let LET_BINDING = NO_BINDING;

const CONST_BINDING = NO_BINDING;

function HOISTED_BINDING(PARAM_BINDING) {
  NO_BINDING;
  VAR_BINDING;
  LET_BINDING;
  CONST_BINDING;
  HOISTED_BINDING;
  PARAM_BINDING;
}
